import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "./components/navbar/Navbar";
import Footer from "./components/footer/Footer";

import { cookies } from "next/headers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function getName(name: string | undefined) {
  if (!name) {
    return undefined;
  }
  const arrEmail = name.split("");
  const index = arrEmail.findIndex((e) => e === "@");
  const result = arrEmail.splice(0, index);
  return result.join("");
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const cookieStore = cookies();
  const tokenData = cookieStore.get("token");
  const token = tokenData?.value;
  const userNameData = cookieStore.get("email");
  const userName = getName(userNameData?.value);

  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar token={token} userName={userName} />
        <main className="layout">{children }</main>
        <Footer />
      </body>
    </html>
  );
}
